### PR TITLE
Support for JAXB 3

### PR DESCRIPTION
**Pull request by adamretter**
This finishes the work that was started by @rlfnb in https://github.com/mojohaus/jaxb2-maven-plugin/pull/166 to update the plugin for JAXB 3, so that all tests and integration tests now pass. Dependencies have also been bought up to date.

It does strike me however that the plugin is named `jaxb2-maven-plugin` and so perhaps we might want to fork this to `jaxb3-maven-plugin` rather than just merging the PR to this repository?

Thoughts?

Closes https://github.com/mojohaus/jaxb2-maven-plugin/issues/165
Closes https://github.com/mojohaus/jaxb2-maven-plugin/pull/166

### CODE REVIEW

**Comment by dizzzz** [comment]
This is a must-have i'd say

**Comment by Chavjoh** [comment]
Can someone merge this PR ? I didn't find any other maven plugin alternative for JAXB 3.0.0, it would be really useful for a lot of people, I think, to have this release.

**Comment by dantran** [comment]
@adamretter  i dont use this plugin any more, but will merge it. 

However, currently running issue where maven-site is too big and prevent maven publisher to push  to github site.  My be we can drop corbutura report

**Comment by adamretter** [comment]
Thanks @dantran. Will it be possible to get a release out too?

**Comment by dantran** [comment]
I am running into a dilemma,   it seems I need to use the latest mojo-parent(60) in order to deploy and release,  however, doing so breaks maven site

At the same time,  windows build on one unit test failure

jaxb3 support fully backward compatible with jaxb2?

**Comment by dantran** [comment]
@adamretter   I am able to fix the maven site issue

**Comment by dantran** [comment]
@adamretter  jaxb3 support fully backward compatible with jaxb2?

**Comment by adamretter** [comment]
@dantran What is the issue that you are seeing?

**Comment by adamretter** [comment]
@dantran I found a single failing test on Windows which is `FileSystemUtilitiesTest#validateRelativizingPaths()`. However, having done some investigation it appears that this test was failing even before my PR.

@dantran Is there anything further I can do to assist in getting a release of this out?

**Comment by adamretter** [comment]
I am afraid that we really needed a release and so I forked the project to https://github.com/evolvedbinary/mojohaus-jaxb-maven-plugin and added the Windows fix https://github.com/mojohaus/jaxb2-maven-plugin/pull/178 and released it here - https://search.maven.org/search?q=com.evolvedbinary.maven.mojohaus

I am hoping it is a short-lived fork and we can replace it with an updated "official" MojoHaus release when that is ready.

**Comment by cristiammercado** [comment]
@adamretter Thanks you much! I was waiting for a long time to this release!

**Comment by adamretter** [comment]
@cristiammercado thanks and you are welcome

**Comment by dantran** [comment]
@adamretter  I staged 3.0.0 and called our a vote at  https://groups.google.com/g/mojohaus-dev/c/1Sdm-4PKjLs

please help testing the staged artifact. and add your vote there

Thanks for works on jaxb 3.0 support.

**Comment by adamretter** [comment]
Thanks @dantran I will take a look and see what I can do.

**Comment by adamretter** [comment]
@dantran It says I don't have permissions to contribute to that Google Group, and I can't find a sign-up link. Any ideas?

**Comment by dantran** [comment]
do you see this ?   https://groups.google.com/g/mojohaus-dev

**Comment by adamretter** [comment]
@dantran got it, thanks!

**Pull request merged**
